### ISSUE TITLE
Couple of issues with the walkthrough

### ISSUE THREAD

**Issue by NeilW** [BeyondScheme/elixir-game_of_life#1]
Hi,

I know how much work there is in constructing walkthroughs, and I really appreciate what you've done with this one.  

However I've been working through and there are a couple of issues at the test run after 'Oh, we forgot about tests.'. Neither GamePrinter, nor Board have been defined at that point so the test run in the walkthrough fails with unknown function errors. 

GamePrinter can be hashed out of game_of_life.ex but the Board definition at that point is just not there. 

And that makes the next section with talks about GameOfLife.Board seem a little strange.

**Comment by ArturT** [comment]
@NeilW Thanks for pointing this out. I created PR with reordered sections. Please let me know if this makes more sense https://github.com/BeyondScheme/BeyondScheme.github.io/pull/8

**Comment by NeilW** [comment]
That seems to do the trick. Thanks for responding.
